[package]
name = "scc-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
sir_core = { path = "../sir_core" }
sir_runner = { path = "../sir_runner" }
scclib = { path = "../scclib" }