[package]
name = "sir_transform"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diagnostics = { path = "../diagnostics" }
iostreams = { path = "../iostreams" }
sir_core = { path = "../sir_core" }