[workspace]

members = [
    "cast",
    "diagnostics",
    "iostreams",
    "scc",
    "sir_core",
    "sir_func",
    "sir_interpreter",
    "sir_lir",
    "sir_low_level",
    "sir_math",
    "sir-opt",
    "sir_runner",
    "sir-runner",
    "parse",
    "utils",
    "xtest",
]
