[package]
name = "sir_low_level"
version = "0.1.0"
edition = "2021"

[dependencies]
diagnostics = { path = "../diagnostics" }
sir_core = { path = "../sir_core" }
sir_transform = { path = "../sir_transform" }