[package]
name = "cast"
version = "0.1.0"
edition = "2021"

[dependencies]
global_counter = "0.2.2"
diagnostics = { path = "../diagnostics" }
iostreams = { path = "../iostreams" }
parse = { path = "../parse" }
utils = { path = "../utils" }
xtest = { path = "../xtest" }